apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_NAME
              value: {{ .Values.postgres.database }}
            - name: DB_USER
              value: {{ .Values.postgres.username }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}

